#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_TEST_DATABASE};
GRANT ALL PRIVILEGES ON ${MYSQL_TEST_DATABASE}.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;
EOF
